[build]
builder = "NIXPACKS"
buildCommand = "npm install && cd backend && npm install && cd ../frontend && npm install && npm run build && cd .. && mkdir -p backend/public && cp -r frontend/build/* backend/public/"

[deploy]
startCommand = "cd backend && node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Ignore landing folder
ignorePaths = ["landing/"]
