@echo off
echo Starting TaskMaster Development Environment...

echo Starting backend server...
start "TaskMaster Backend" cmd /k "cd backend && npm start"

echo Waiting 5 seconds for backend to start...
timeout /t 5 /nobreak

echo Starting frontend development server...
start "TaskMaster Frontend" cmd /k "cd frontend && npm start"

echo Development servers are starting...
echo Backend: http://localhost:5000
echo Frontend: http://localhost:3000
echo.
echo Press any key to close this window...
pause